# Generated by Django 4.1.7 on 2023-04-18 22:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_book_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='BioText',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='read',
            name='Score',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
