# Generated by Django 4.1.7 on 2023-04-18 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_book_description_alter_profile_biotext_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
