# Generated by Django 4.1.7 on 2023-04-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_profile_firstname_profile_lastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='FirstName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='LastName',
            field=models.CharField(max_length=100),
        ),
    ]
